default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>

development:
  <<: *default
  database: plato_dashboard_development

test:
  <<: *default
  database: plato_dashboard_test

production:
  <<: *default
  database: plato_dashboard_production
  username: plato_dashboard
  password: <%= ENV['PLATO_DASHBOARD_DATABASE_PASSWORD'] %>
